force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Assigned_Amount__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Amount__c</fullName>
    <description>Estimated project cost based on current assigned hours per resource</description>
    <label>Assigned Amount</label>
    <summarizedField>Project_Line_Item__c.Assigned_Amount__c</summarizedField>
    <summaryForeignKey>Project_Line_Item__c.Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Estimated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Amount__c</fullName>
    <label>Estimated Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Squad_Lead__c.field-meta.xml
<CustomField>
    <fullName>Squad_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Squad Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Assigned_Resource__c/Project_Assigned_Resource__c.object-meta.xml
<CustomObject>
    <label>Project Assigned Resource</label>
    <nameField>
        <label>Project Assigned Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assigned Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Assigned_Resource__c/fields/Assigned_Amount__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Amount__c</fullName>
    <label>Assigned Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Assigned_Resource__c/fields/Project_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Project_Line_Item__c</fullName>
    <label>Project Line Item</label>
    <referenceTo>Project_Line_Item__c</referenceTo>
    <relationshipLabel>Project Assigned Resources</relationshipLabel>
    <relationshipName>Project_Assigned_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Assigned_Resource__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Assigned_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Line_Item__c/Project_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Project Line Item</label>
    <nameField>
        <label>Project Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Line_Item__c/fields/Assigned_Amount__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Amount__c</fullName>
    <description>The cost of the resources currently assigned to this Project Line Item</description>
    <label>Assigned Amount</label>
    <summarizedField>Project_Assigned_Resource__c.Assigned_Amount__c</summarizedField>
    <summaryForeignKey>Project_Assigned_Resource__c.Project_Line_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project_Line_Item__c/fields/Assigned_Hours__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Hours__c</fullName>
    <label>Assigned_Hours</label>
    <summarizedField>Project_Assigned_Resource__c.Assigned_Hour__c</summarizedField>
    <summaryForeignKey>Project_Assigned_Resource__c.Project_Line_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project_Line_Item__c/fields/Estimated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Amount__c</fullName>
    <label>Estimated Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Line_Item__c/fields/Estimated_Hours__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Hours__c</fullName>
    <description>Estimated hours by role</description>
    <label>Estimated Hours</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Line_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Line Items</relationshipLabel>
    <relationshipName>Project_Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectResourcesValidations.cls
public with sharing class ProjectResourcesValidations {

    //Retorna true si el proyecto pasado por parametro tiene un unico squad lead. De lo contrario retorna false
    public static boolean hasUniqueSquadLead(Project__c project){

        List<Id> userIds = ProjectResourcesHelper.getUserIdsOfProject(project.Id);
        if(project.Squad_Lead__c ==null){
            return false;
        }    
        else{
            if(!userIds.contains(project.Squad_Lead__c))
                return false;
            return true;   
        }
    }
    
    //retorna true si el proyecto tiene asignadas la totalidad de horas requeridas por el equipo de ventas
    public static boolean projectIsFull(Project__c project){
        Project__c projectWithLineItems = [SELECT id, (SELECT id, Assigned_Hours__c, Estimated_Hours__c FROM Project_Line_Items__r) FROM Project__c WHERE id=:project.id];
        List<Project_Line_Item__c> projectLineItemList = projectWithLineItems.Project_Line_Items__r;
       
        for(Project_Line_Item__c lineItem:projectLineItemList){
            if(lineItem.Assigned_Hours__c < lineItem.Estimated_Hours__c)
                return false;
        }
        return true;
    }
    // Retorna true si el proyecto es rentable en base a su costo estimado y real
    public static boolean isProfitable(Project__c project){
            if(project.Assigned_Amount__c > project.Estimated_Amount__c)
                return false;
            return true;
    }

    public static void validatePARs(List<Project_Assigned_Resource__c> PARsList){
        Map<Id,User> PARsByUserId = new Map<Id,User>([SELECT Id, (SELECT id,User__c,User__r.Name,Start_Date__c,End_Date__c FROM Project_Assigned_Resources__r WHERE End_Date__c>=:Date.Today()) FROM User]);
        Map<Id,Project_Line_Item__c> PLIsByPLIId = new Map<Id,Project_Line_Item__c>([SELECT Project__r.Start_Date__c, Project__r.End_Date__c FROM Project_Line_Item__c]);
        for(Project_Assigned_Resource__c item :PARsList){
            Project_Line_Item__c currentPLI = PLIsByPLIId.get(item.Project_Line_Item__c);
            User UserPARs = PARsByUserId.get(item.User__c);
            List<Project_Assigned_Resource__c> PARs = UserPARs.Project_Assigned_Resources__r;
            
            String error = ProjectResourcesValidations.validateAssignedDates(item.Start_Date__c,item.End_Date__c,currentPLI,PARs);
            if( error!= null)
                item.addError(error);
          }
    
    }

    public static String validateAssignedDates(Date startDate,Date endDate,Project_Line_Item__c currentPLI,List<Project_Assigned_Resource__c> userAssignedResources){
        String error;
        if(startDate==null || endDate ==null){
            return 'Se deben asignar ambas fechas';
        }
        if(endDate<startDate){
            error='La fecha de fin de la asignacion no puede ser anterior a la fecha de inicio.';
            return error;
        }     
        if(endDate<Date.today() || startDate<Date.today()){
            error='Las fechas de inicio y fin del proyecto no pueden ser fechas pasadas';
            return error;
        }
		String dayOfStartDate = Util.getDayOfWeek(startDate);
        String dayOfEndDate= Util.getDayOfWeek(endDate);

        // Valida que las fechas no sean sabado o domingo
        
        if(dayOfStartDate == 'Saturday' || dayOfStartDate == 'Sunday'){
                if(dayOfEndDate =='Saturday' || dayOfEndDate == 'Sunday'){
                    error='No se pueden asignar dias no laborales como fecha de termino del proyecto';
                    return error;
                }
            error='No se pueden asignar dias no laborales como fecha de inicio del proyecto';
            return error;		
        }

        Date projectStartDate = currentPLI.Project__r.Start_Date__c; 
        Date projectEndDate = currentPLI.Project__r.End_Date__c;

        if(startDate<projectStartDate || endDate>projectEndDate){
            error='No se pueden asignar recursos fuera del rango de fechas del proyecto';
            return error;
        }
        
        for(Project_Assigned_Resource__c assignedResource : userAssignedResources){
            Date resourceStartDate = assignedResource.Start_Date__c; 
            Date resourceEndDate = assignedResource.End_Date__c;   
            if(startDate<=resourceEndDate && endDate>=resourceStartDate){
                error='No pueden asignarse las fechas seleccionadas porque no estan disponibles para ' + assignedResource.user__r.Name;
                return error;
            }
        }
            
		return error;     
    }
}