force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Assigned_Resource__c/Project_Assigned_Resource__c.object-meta.xml
<CustomObject>
    <label>Project Assigned Resource</label>
    <nameField>
        <label>Project Assigned Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assigned Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Assigned_Resource__c/fields/Assigned_Hour__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Hour__c</fullName>
    <label>Assigned Hour</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Assigned_Resource__c/fields/Project_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Project_Line_Item__c</fullName>
    <label>Project Line Item</label>
    <referenceTo>Project_Line_Item__c</referenceTo>
    <relationshipLabel>Project Assigned Resources</relationshipLabel>
    <relationshipName>Project_Assigned_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Line_Item__c/Project_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Project Line Item</label>
    <nameField>
        <label>Project Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Line_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Line Items</relationshipLabel>
    <relationshipName>Project_Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testclass.cls
public class testclass {
	
    static List<Project_Line_Item__c> getLineItemsFromProjectId (Id projectId){
        
        List<Project_Line_Item__c>  projectLineItemList= 
        [SELECT Project__c,Role__c, (SELECT Id,Start_Date__c, End_Date__c,Assigned_Hour__c FROM Project_Assigned_Resources__r ) 
        FROM Project_Line_Item__c WHERE id =:projectId];
        
        List<String> rolesList  = new List<String>();
        
 		for(Project_Line_Item__c p : projectLineItemList){
            rolesList.add(p.Role__c);
            rolesList.add(p.Role__c);
        }
	return projectLineItemList;
    }//Fin Metodo getLineItemsFromProjectId
     
    
    public static List<Date> getDates(){
        List<Date> fechas = new List<Date>();
        for(Integer i = 0; i<20; i++){
            fechas.add(Date.today()+ i);
        }
   		return fechas;
    }
    

}